apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  labels:
    app: openspeedtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
      - name: openspeedtest
        image: openspeedtest/latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
spec:
  type: NodePort
  selector:
    app: openspeedtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090