apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BradSainty/homelab.git
    targetRevision: HEAD
    path: nginx
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: webserver
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
